server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # This allows React Router to handle URLs
        try_files $uri $uri/ /index.html;
    }
}
